"""Keys: cost and description were added

Revision ID: c920c884f134
Revises: 
Create Date: 2023-04-23 19:13:10.824062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c920c884f134'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('cost', sa.Integer(), nullable=True))
    op.add_column('items', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'description')
    op.drop_column('items', 'cost')
    # ### end Alembic commands ###
